# ============================================================
# VERA — Configuración PostgreSQL (Neon)
# ============================================================

# --- Conexión a Neon ---
spring.datasource.url=jdbc:postgresql://ep-holy-wind-aklqwzsa-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_rN9t0LpBlUIG
spring.datasource.driver-class-name=org.postgresql.Driver

# --- SSL requerido por Neon ---
spring.datasource.hikari.data-source-properties.sslmode=require

# --- Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Pool de conexiones (ajustado para Neon) ---
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.keepalive-time=30000

# --- Servidor ---
server.port=8080

# --- JWT ---
jwt.secret=YmFzZTY0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTMyLWJ5dGVzLWxvbmctZm9yLWhtYWMyNTY=
jwt.expiration=86400000

# --- Google Safe Browsing ---
google.safe-browsing.api-key=AIzaSyAWaIYOlqtgvQe2ovqP3NeaEPfqsXLCDR8

# --- Google Gemini ---
google.gemini.api-key=AIzaSyARVgHi8CvrcdHnpa3Y26HP5yLoXNGkChk
google.gemini.model=gemini-2.5-flash
google.gemini.fallback-model=gemini-3.1-flash-lite

# --- Mail - Reset Password ---

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=vera.notificaciones.app@gmail.com
spring.mail.password=citj eisp xqob cnhh

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true