-- =========================================================
-- PROCEDENCIA U ORIGEN DEL MENSAJE
-- =========================================================

CREATE TABLE message_sources (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- =========================================================
-- NIVELES DE RIESGO DE SEGURIDAD
-- =========================================================

CREATE TABLE risk_levels (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- =========================================================
-- TIPOS DE RELACIÓN
-- =========================================================

CREATE TABLE relationship_types (
    id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

-- =========================================================
-- MENSAJES RECIBIDOS
-- =========================================================

CREATE TABLE messages (

    id UUID PRIMARY KEY,

    user_id BIGINT NOT NULL,

    content TEXT NOT NULL,

    source_id VARCHAR(50) NOT NULL,

    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_messages_source
        FOREIGN KEY (source_id)
        REFERENCES message_sources(id),

    CONSTRAINT fk_messages_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

-- =========================================================
-- ANÁLISIS DE MENSAJES
-- =========================================================

CREATE TABLE analyses (

    id UUID PRIMARY KEY,

    message_id UUID NOT NULL,

    risk_level_id VARCHAR(50) NOT NULL,

    suspicious_patterns TEXT NOT NULL,

    recommendation TEXT NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_analyses_message
        FOREIGN KEY (message_id)
        REFERENCES messages(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_analyses_risk_level
        FOREIGN KEY (risk_level_id)
        REFERENCES risk_levels(id)
);

-- =========================================================
-- PERSONAS PROTEGIDAS
-- =========================================================

CREATE TABLE user_caregivers (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,

    full_name VARCHAR(255) NOT NULL,

    relationship_type_id VARCHAR(50) NOT NULL,

    phone VARCHAR(50),

    email VARCHAR(255),

    high_risk_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE,

    weekly_summary_enabled BOOLEAN NOT NULL DEFAULT FALSE,

    notification_sensitivity VARCHAR(20)
        NOT NULL
        DEFAULT 'MEDIUM',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_caregivers_user
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_caregivers_relationship
        FOREIGN KEY (relationship_type_id)
        REFERENCES relationship_types(id),

    CONSTRAINT chk_notification_sensitivity
        CHECK (
            notification_sensitivity IN (
                'LOW',
                'MEDIUM',
                'HIGH'
            )
        )
);

-- =========================================================
-- ALERTAS DE RIESGO
-- =========================================================

CREATE TABLE risk_alerts (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    analysis_id UUID NOT NULL,

    caregiver_id BIGINT NOT NULL,

    is_received BOOLEAN NOT NULL DEFAULT FALSE,

    sent_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_alerts_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES analyses(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_alerts_caregiver
        FOREIGN KEY (caregiver_id)
        REFERENCES user_caregivers(id)
        ON DELETE CASCADE
);

-- =========================================================
-- ÍNDICES
-- =========================================================

CREATE INDEX idx_user_caregivers_user
ON user_caregivers(user_id);

CREATE INDEX idx_risk_alerts_not_received
ON risk_alerts(caregiver_id)
WHERE is_received = FALSE;

-- =========================================================
-- DATOS INICIALES
-- =========================================================

-- ORÍGENES DE MENSAJES

INSERT INTO message_sources (id, name) VALUES
    ('UNKNOWN', 'Origen Desconocido'),
    ('WHATSAPP', 'WhatsApp'),
    ('TELEGRAM', 'Telegram');

-- NIVELES DE RIESGO

INSERT INTO risk_levels (id, name) VALUES
    ('UNDEFINED', 'Sin Definir'),
    ('LOW', 'Bajo'),
    ('MEDIUM', 'Medio'),
    ('HIGH', 'Alto');

-- TIPOS DE RELACIÓN

INSERT INTO relationship_types (id, name) VALUES
    ('UNDEFINED', 'Sin Definir'),
    ('FAMILY_MEMBER', 'Familiar'),
    ('TRUSTED_CONTACT', 'Contacto de Confianza'),
    ('PROFESSIONAL', 'Soporte Profesional');