-- Procedencia u origen del mensaje
CREATE TABLE message_sources (
                                 id VARCHAR(50) PRIMARY KEY,
                                 name VARCHAR(100) NOT NULL
);

-- Niveles de riesgo de seguridad
CREATE TABLE risk_levels (
                             id VARCHAR(50) PRIMARY KEY,
                             name VARCHAR(100) NOT NULL
);

-- Tipos de relación simplificados para Cuidadores
CREATE TABLE relationship_types (
                                    id VARCHAR(50) PRIMARY KEY,
                                    name VARCHAR(100) NOT NULL
);


-- Tabla de Mensajes recibidos
CREATE TABLE messages (
                          id UUID PRIMARY KEY,
                          user_id BIGINT NOT NULL,
                          content TEXT NOT NULL,
                          source_id VARCHAR(50) NOT NULL,
                          received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_messages_source FOREIGN KEY (source_id) REFERENCES message_sources(id),
                          CONSTRAINT fk_messages_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Tabla de Análisis
CREATE TABLE analyses (
                          id UUID PRIMARY KEY,
                          message_id UUID NOT NULL,
                          risk_level_id VARCHAR(50) NOT NULL,
                          suspicious_patterns TEXT NOT NULL,
                          recommendation TEXT NOT NULL,
                          created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          CONSTRAINT fk_analyses_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
                          CONSTRAINT fk_analyses_risk_level FOREIGN KEY (risk_level_id) REFERENCES risk_levels(id)
);

-- Tabla de Cuidadores (Relación autorreferencial de usuarios con datos de contacto específicos)
CREATE TABLE user_caregivers (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id BIGINT NOT NULL,
                                 caregiver_id BIGINT NOT NULL,
                                 relationship_type_id VARCHAR(50) NOT NULL,
                                 phone VARCHAR(50) NOT NULL,
                                 email VARCHAR(255) NOT NULL,
                                 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                 CONSTRAINT fk_caregivers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_caregivers_caregiver FOREIGN KEY (caregiver_id) REFERENCES users(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_caregivers_relationship FOREIGN KEY (relationship_type_id) REFERENCES relationship_types(id),

                                 CONSTRAINT uk_user_caregiver UNIQUE (user_id, caregiver_id),
                                 CONSTRAINT chk_not_self_caregiver CHECK (user_id <> caregiver_id)
);

-- Tabla de Alertas de Riesgo
CREATE TABLE risk_alerts (
                             id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                             analysis_id UUID NOT NULL,
                             caregiver_id BIGINT NOT NULL,
                             is_received BOOLEAN NOT NULL DEFAULT FALSE,
                             sent_at TIMESTAMP,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_alerts_analysis FOREIGN KEY (analysis_id) REFERENCES analyses(id) ON DELETE CASCADE,
                             CONSTRAINT fk_alerts_caregiver FOREIGN KEY (caregiver_id) REFERENCES users(id) ON DELETE CASCADE
);


CREATE INDEX idx_user_caregivers_user ON user_caregivers(user_id);
CREATE INDEX idx_risk_alerts_not_received ON risk_alerts(caregiver_id) WHERE is_received = FALSE;


-- Carga de Orígenes de Mensajes
INSERT INTO message_sources (id, name) VALUES
                                           ('UNKNOWN', 'Origen Desconocido'),
                                           ('WHATSAPP', 'WhatsApp'),
                                           ('TELEGRAM', 'Telegram');

-- Carga de Niveles de Riesgo
INSERT INTO risk_levels (id, name) VALUES
                                       ('UNDEFINED', 'Sin Definir'),
                                       ('LOW', 'Bajo'),
                                       ('MEDIUM', 'Medio'),
                                       ('HIGH', 'Alto');

-- Carga de los 3 Tipos de Relación Estándar y Simplificados
INSERT INTO relationship_types (id, name) VALUES
                                              ('UNDEFINED', 'Sin Definir'),
                                              ('FAMILY_MEMBER', 'Familiar'),
                                              ('TRUSTED_CONTACT', 'Contacto de Confianza'),
                                              ('PROFESSIONAL', 'Soporte Profesional');
